export const signUpText = 'Sign Up';
export const loginText = 'Login';
export const resetPasswordText = 'Reset Password';
export const userType = 'User Type';
export const nameText = 'Name';
export const emailText = 'Email';
export const passwordText = 'Password';
export const passwordConfirmationText = 'Password confirmation';
export const submitText = 'Submit';
export const today = 'Today';

export const locale = {
  new: 'NEW',
  writeYourFirstMessage: 'No messages yet',
  chat: 'Chat',
  notReviewsYet: 'No reviews yet',
  recover: 'Recover',
  min: 'Min',
  session: 'Session',
  payments: 'Payments',
  cancellationFee: 'Cancellation Fee',
  cancel: 'Cancel',
  call: 'Call',
  creatingACall: 'Dialing...\nYou should receive an incoming call shortly.',
  somethingWrong: 'Something went wrong. Please try again.',
  text: 'Text',
  areYourSure: 'Are your sure?',
  youWillNotBeCharged: 'You will not be charged a cancellation fee',
  oopsNo: 'oops, no',
  continue: 'continue',
  agent: 'Agent',
  manager: 'Manager',
  click: 'Click',
  here: 'Here',
  show: 'Show',
  book: 'Book',
  today: 'Today',
  welcome: 'WELCOME TO SELFTAPE NOW!\n WE SHOOT. YOU KILL.',
  started: "Let's Get Started!",
  addPhoto: 'Add Photo',
  next: 'Next',
  errorText: '*ZIP code should be 5 digit long',
  todaysAudition: 'TODAY\'S AUDITION',
  send: 'SEND',
  weWillNotifyYou: 'We will notify you when',
  confirmationOfBooking: 'Confirmation of Booking',
  confirmsSession: 'confirms the session',
  when: 'When:',
  time: 'Time:',
  where: 'Where:',
  getThereWithUber: 'GET THERE WITH UBER',
  getThereWithLyft: 'GET THERE WITH LYFT',
  uploadPdf: 'Upload PDF',
  uploadImage: 'Upload Image',
  uploadSides: 'Upload Sides',
  details: 'Details',
  pastSessions: 'Past Sessions',
  upcomingSessions: 'Upcoming sessions',
  selfTape: 'SELF-TAPE',
  edit: 'EDIT',
  bookAgain: 'Book Again',
  review: 'Review',
  noBookData: 'No book data',
  helpCenter: 'Help Center aka FAQ',
  tutorial: 'Tutorial',
  reportAnIssue: 'Report an issue',
  legal: 'Legal',
  privacyPolicy: 'Privacy Policy',
  termsAndConditions: 'Terms & Conditions',
  help: 'Help',
  version: 'Version 1.0.6',
  copyrightYear: '© 2017',
  confirmation: 'Confirmation',
  youWillBeTapping: 'You will be taping',
  client: 'Client:',
  yourLocation: 'Your location:',
  downloadSides: 'Download Sides',
  download: 'Download',
  pay: 'Pay',
  changePaymentMethod: 'Change payment method',
  taxesAndFees: 'Taxes & Fees:',
  vendorCharge: 'Vendor Charge:',
  attachments: 'Attachments',
  skip: 'Skip Uploading',
  checkIn: 'CHECK IN',
  checkOut: 'CHECK OUT',
  noSessionsFound: 'No sessions found',
  checkInOutPage: 'Check In/Out',
  setYourServicePrice: 'Set Your Service/Price',
  serviceDescription: 'ADD A NOTE - This will tell clients what to expect from this service and how to use it. Ex: This service is based on a per hour rate.',
};


export const weekDays = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
];

export const months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];
