import { StyleSheet } from 'react-native';
import { HelveticaLight } from '../constants/fontConstants';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignSelf: 'stretch',
  },
  containerText: {
    flexDirection: 'row',
    marginTop: 20,
    paddingRight: 28,
  },
  dot: {
    width: 4,
    height: 4,
    backgroundColor: 'black',
    borderRadius: 4 / 2,
    margin: 6,
    marginLeft: 8,
    marginRight: 12,
  },
  dottedText: {
    fontFamily: HelveticaLight,
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: 1,
    alignSelf: 'stretch',
    paddingRight: 28,
  },
  imageStyle: {
    marginBottom: 20,
  },
  signUpBlock: {
    backgroundColor: 'black',
    marginTop: 50,
    paddingTop: 10,
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 30,
  },
  signUpBlockText: {
    color: 'white',
    fontWeight: '600',
    fontFamily: HelveticaLight,
    fontSize: 16,
    letterSpacing: 1,
  },
  becomeExpertButtons: {
    marginTop: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  becomeButton: {
    backgroundColor: '#3b88cd',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 15,
    paddingRight: 15,
    borderColor: '#6993b0',
    borderWidth: 2,
    height: 35,
    width: '100%',
  },
  becomeButtonText: {
    color: 'white',
    fontWeight: '600',
    fontFamily: HelveticaLight,
    letterSpacing: 1,
    fontSize: 12,
  },
  inputStyle: {
    height: 35,
    backgroundColor: '#a0a09f',
    paddingLeft: 6,
    paddingRight: 6,
    borderColor: '#ffffff',
    borderWidth: 2,
    width: 100,
    alignItems: 'center',
  },
  imageText: {
    position: 'absolute',
    width: '70%',
    left: 70,
    top: 50,
    color: 'white',
    fontSize: 24,
    fontFamily: HelveticaLight,
    fontWeight: '600',
    letterSpacing: 1,
  },
});
