import { StyleSheet } from 'react-native';
import { COLOR_GREY, COLOR_GREY_4B5053 } from './common';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignSelf: 'stretch',
  },
  containerBlock: {
    marginTop: 10,
    marginRight: 15,
    marginBottom: 5,
    marginLeft: 15,
    borderColor: COLOR_GREY,
    borderWidth: 1,
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    paddingTop: 20,
    paddingBottom: 25,
  },
  containerBlockWeekDays: {
    marginTop: 10,
    marginRight: 15,
    marginBottom: 5,
    marginLeft: 15,
    borderColor: COLOR_GREY,
    borderWidth: 1,
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 7,
    paddingRight: 0,
  },
  auditionTitle: {
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'Helvetica-Light',
  },
  auditionTime: {
    display: 'flex',
    flexDirection: 'row',
    marginTop: 8,
  },
  auditionTimeActive: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'Helvetica-Light',
  },
  auditionTimeUnActive: {
    fontSize: 12,
    fontWeight: '400',
    color: '#7c8d90',
    fontFamily: 'Helvetica-Light',
  },
  auditionCost: {
    marginTop: 8,
    fontFamily: 'Helvetica-Light',
    fontSize: 20,
    fontWeight: '400',
  },
  auditionStats: {
    display: 'flex',
    flexDirection: 'row',
    alignSelf: 'stretch',
    justifyContent: 'space-around',
  },
  auditionStatsContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 25,
    width: 100,
  },
  auditionStatsCount: {
    fontFamily: 'Helvetica-Light',
    fontSize: 20,
    fontWeight: '400',
  },
  auditionStatsTitle: {
    fontSize: 10,
    fontWeight: '400',
    fontFamily: 'Helvetica-Light',
    color: COLOR_GREY_4B5053,
  },
  statsName: {
    marginTop: 5,
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Helvetica-Light',
  },
  statsPercentages: {
    marginTop: 20,
    fontFamily: 'Helvetica-Light',
    fontSize: 20,
    fontWeight: '400',
  },
  statsSubtitle: {
    marginTop: 5,
    fontSize: 11,
    color: COLOR_GREY_4B5053,
    fontWeight: '400',
    fontFamily: 'Helvetica-Light',
  },
  statsAdditionalInfo: {
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  statsAdditionalBottomContainers: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    width: 100,
  },
  statsAdditionalInfoRating: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsAdditionalInfoRatingStar: {
    width: 18,
    height: 18,
    marginRight: 3,
  },
  statsRatingCount: {
    fontSize: 20,
    fontWeight: '400',
    fontFamily: 'Helvetica-Light',
  },
  statsSubtitleBottom: {
    marginTop: 5,
    fontSize: 11,
    color: COLOR_GREY_4B5053,
    fontWeight: '400',
    fontFamily: 'Helvetica-Light',
  },
  containerBlockWeekDaysImage: {
    height: 190,
    width: '95%',
  },
  weekTitle: {
    fontSize: 14,
    color: '#000',
    marginRight: 7,
    width: 13,
    textAlign: 'center',
  },
  singleDayRow: {
    width: '100%',
    marginBottom: 5,
    flexDirection: 'row',
  },
  singleDayColumn: {
    flex: 1,
    backgroundColor: '#d5dee5',
    marginRight: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightningImage: {
    width: 25,
    height: 20,
  },
});
