import { StyleSheet } from 'react-native';
import { COLOR_GREY, COLOR_GREY_D1CECF, COLOR_GREY_5E5E60, COLOR_WHITE, COLOR_GREEN_82DAB7, COLOR_BLUE_73A5D0 } from './common';
import { HelveticaLight } from '../constants/fontConstants';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignSelf: 'stretch',
    backgroundColor: '#e3e3e3',
  },
  containerTopMenu: {
    height: 40,
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    borderColor: COLOR_GREY,
    borderBottomWidth: 2,
  },
  selectedTopButton: {
    fontWeight: '700',
  },
  containerDate: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    height: 35,
    padding: 7,
    paddingHorizontal: 15,
    backgroundColor: COLOR_GREY_D1CECF,
    borderColor: '#d2cfd2',
    borderTopWidth: 2,
    borderBottomWidth: 2,
    marginTop: 10,
    marginBottom: 2,
  },
  calendarIcon: {
    width: 15,
    height: 15,
    marginRight: 5,
  },
  containerClient: {
    marginHorizontal: 10,
    marginTop: 10,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: 'transparent',
    paddingLeft: 3,
    paddingRight: 3,
  },
  status: {
    height: '100%',
    width: 13,
    borderTopLeftRadius: 3,
    borderBottomLeftRadius: 3,
  },
  textDate: {
    color: COLOR_GREY_5E5E60,
    fontFamily: HelveticaLight,
    fontWeight: '900',
  },
  containerClientAvatar: {
    height: 58,
    width: 58,
    backgroundColor: COLOR_WHITE,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 4,
    borderRadius: 3,
    marginRight: 10,
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  containerClientRight: {
    height: 58,
    backgroundColor: COLOR_WHITE,
    alignSelf: 'stretch',
    flex: 1,
    borderRadius: 3,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  containerClientRightJustifyContainer: {
    alignSelf: 'stretch',
    justifyContent: 'space-between',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  containerClientInfo: {
    height: '100%',
    justifyContent: 'space-between',
    padding: 7,
    paddingRight: 10,
    flex: 1,
  },
  containerClientInfoLeft: {
    flex: 1,
    height: '100%',
    justifyContent: 'space-between',
  },
  containerClientInfoRight: {
    flex: 1,
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  timeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 20,
  },
  clientTime: {
    fontWeight: '600',
    fontFamily: HelveticaLight,
    fontSize: 15,
    color: '#68686a',
  },
  clientName: {
    fontFamily: HelveticaLight,
    fontSize: 14,
    fontWeight: '800',
    color: '#464646',
  },
  bookLength: {
    fontFamily: HelveticaLight,
    fontSize: 14,
    fontWeight: '800',
    marginLeft: 25,
    color: COLOR_GREEN_82DAB7,
  },
  sessionStatus: {
    fontFamily: HelveticaLight,
    fontWeight: '400',
    fontSize: 14,
    color: COLOR_BLUE_73A5D0,
    alignSelf: 'flex-end',
  },
  sessionStatusContainer: {
    alignSelf: 'flex-end',
  },
});
