const firebasecommunities = [
  {
    companies: [{
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FActingClasses.jpeg?alt=media&token=46129ed7-bc9d-4037-99a6-14bb55eb70dc',
        sub_title: 'Explore. Discover. Experience. Express.',
        text: 'Our teachers provide a creative environment devoted to supporting the transformative experience and expression of the empathetic imagination.',
        title: 'Acting Classes',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FDianaCastlesVideoLecture.jpeg?alt=media&token=1d3c50a6-2e31-4b1a-993d-f749be381438',
        sub_title: 'Widen Your Empathetic Embrace.',
        text: "Diana Castle's on - demand lectures inspire, encourage and explore the \"how to's\" of living your imagined life.Watch anywhere, anytime!",
        title: "Diana Castle's Video Lectures",
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FimaginedLife.png?alt=media&token=4528e64c-b10e-4e2f-a39a-e40ec53ca632',
      fontColor: '#6421b7',
      fontFamilyText: 'SukhumvitSetBold',
      mail: 'www.theimaginedlife.com',
      name: 'Imagined Life Acting School',
      rating: 5,
      category: 'acting',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FLynetteArticle1.jpg?alt=media&token=04746248-a603-4112-b3e4-b7d9cd01933b',
        sub_title: 'Helping you to discover your voice as an actor',
        text: 'Helping you to audition successfully, and helping you to stay on track and avoid setbacks so that you can achieve your goal of working consistently in the industry.',
        title: 'We are there for you every step of the way!',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FLynetteArticle2.jpg?alt=media&token=2b9b9e53-a1c3-4755-ab1b-776a5f603158',
        sub_title: 'From beginning to advanced',
        text: 'We focus on your specific needs and training for you to become a successful actor. Our programs are tailor-made for you to tackle critical areas holding you back.',
        title: 'Every program is tailor-made!',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FLynette.png?alt=media&token=30488a05-ead6-4848-a482-1b7fbc5e4a36',
      fontColor: '#a21419',
      fontFamilyText: 'AvenirLight',
      mail: 'lynettestudioassistant@gmail.com',
      name: 'Lynette McNiell Acting Studio',
      rating: 5,
      category: 'acting',
      width: 200,
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FScottSedita1.png?alt=media&token=e41d0bae-f894-4b23-820a-a245dc376509',
        sub_title: 'Every Moment. Every Day. Every Audition.',
        text: 'Scott talks about The Eight Characters of Comedy',
        title: 'The Gregory Mantell Show',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FScottSedita2.png?alt=media&token=a53ccffb-7934-4436-9e9b-3b8fcac1afbb',
        sub_title: 'Every Moment. Every Day. Every Audition.',
        text: 'Scott gives actors some tips and advice.',
        title: 'Argentum’s Headshot Cafe',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FScottSedita.jpg?alt=media&token=e4e4fdbb-d836-481b-904c-92e3b52b18e5',
      fontColor: '#6894af',
      fontFamilyText: 'ERBukinistMacBold',
      mail: 'scottsedita@gmail.com',
      name: 'Scott Sedita Acting School',
      rating: 5,
      category: 'vocal',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FLeeStrsberg1.jpg?alt=media&token=ac6cff92-14b4-4245-acf6-e7da349bdc2d',
        sub_title: 'Every Moment. Every Day.',
        text: 'As the only school in the world that teaches Lee Strasberg’s work in its consummate form, The Lee Strasberg Theatre & Film Institute® is the home for all actors seeking to delve into Method Acting and its tradition of training some of the world’s most brilliant and truthful actors.',
        title: 'DISCOVER THE METHOD',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FLeeStresberg.png?alt=media&token=ca40e12f-307a-4ade-ae75-ec3ce7bff4e1',
      fontColor: '#6d9062',
      fontFamilyText: 'BaskervilleItalic',
      mail: 'losangeles@strasberg.com',
      name: 'Lee Strasberg School of Acting',
      rating: 5,
      category: 'acting',
      width: 280,
    }],
    image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/icon%2Fcomunities%2Ftutor.png?alt=media&token=2e04452a-fa5a-4590-9487-9563f7b21ed4',
    name: 'CLASSES/COACHES',
  }, {
    companies: [{
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FDamumaly1.jpg?alt=media&token=907a15c8-5f37-4c34-b850-db9654b2780b',
        sub_title: 'Every Moment. Every Day. I know how nerve racking photo shoots can be. So, you can be assured we will shoot until you are absolutely thrilled. I do my own retouching and I will also work with you until you are completely satisfied with the finished images. Of course, if you have a retoucher or do your own retouching, I can provide you with the original raw files. As the only school in the world that teaches Lee Strasberg’s work in its consummate form, The Lee Strasberg Theatre & Film Institute® is the home for all actors seeking to delve into Method Acting and its tradition of training some of the world’s most brilliant and truthful actors.',
        title: 'Jason',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FDamumaly2.jpg?alt=media&token=8cf9fea3-e47f-40ea-b16b-14910eb81ae2',
        sub_title: 'Every Moment. Every Day.',
        text: 'I know how nerve racking photo shoots can be. So, you can be assured we will shoot until you are absolutely thrilled. I do my own retouching and I will also work with you until you are completely satisfied with the finished images. Of course, if you have a retoucher or do your own retouching, I can provide you with the original raw files.',
        title: 'The Ahleya Fuller Shoot',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FDamumaly.png?alt=media&token=19ffe921-5741-437b-a4df-74c3b32e8b8a',
      fontColor: '#6421b7',
      fontFamilyText: 'SukhumvitSetBold',
      mail: 'damumalikphoto@gmail.com',
      name: 'Damu Malik Photography',
      rating: 5,
      category: 'photography',
      width: 200,
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FBrandonEspy1.jpeg?alt=media&token=7fdc0614-94f2-4b01-9e7e-1ccd0b92f841',
        sub_title: 'Every Moment. Every Day.',
        text: 'Brandon Espy grew up outside of Los Angeles in Diamond Bar, CA under a Behavioral Psychologist for a father and a mother who works in Merchandise Marketing. Graduating from the University of San Diego with a Bachelor of Art in Communication Studies in May 2010, he made the city of LA his home where he found his love for storytelling.',
        title: 'Brandon Espy',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FBrandonEspy.png?alt=media&token=dfa1d66b-2ed0-40d6-8b9f-1709018bb3a8',
      fontColor: '#a21419',
      fontFamilyText: 'AvenirLight',
      mail: 'brandonespyphoto@gmail.com',
      name: 'Brandon Espy Photography',
      rating: 5,
      category: 'photography',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FIrisRay1.jpg?alt=media&token=2bcc9e64-4a0c-4fa5-b937-aec3da8a9522',
        sub_title: 'Every Moment. Every Day.',
        text: "I inherited the good manners, but not the accent. I take photographs because I'm a nerd.It lets me express my love for all things cute, kitschy, and crude.",
        title: 'Iris Ray',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FIrisRay.png?alt=media&token=81df123a-8d0d-4296-95c4-825194fd3a87',
      fontColor: '#6894af',
      fontFamilyText: 'ERBukinistMacBold',
      mail: 'iris@irisrayphoto.com',
      name: 'Iris Ray',
      rating: 5,
      category: 'photography',
      width: 150,
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FRikerbrothers1.png?alt=media&token=5144a727-33a5-4177-8de9-8e09dc87dc70',
        sub_title: 'Every Day.',
        text: 'I Born in Iowa City and growing up in a small town west of Chicago, twin brothers Derek and Drew Riker were introduced to photography by their father who was always taking pictures. After graduating from the University of Illinois with degrees in Economics and both taking jobs in Chicago, they were left feeling unfulfilled in the business world. Their lives would change while on vacation in Miami Beach when they were scouted to be models.',
        title: 'Riker Brothers',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FRikerbrothers2.png?alt=media&token=0426c601-9070-42a8-8c61-4188f2bb3539',
        sub_title: 'Every Moment',
        text: 'Born in Iowa City and growing up in a small town west of Chicago, twin brothers Derek and Drew Riker were introduced to photography by their father who was always taking pictures. After graduating from the University of Illinois with degrees in Economics and both taking jobs in Chicago, they were left feeling unfulfilled in the business world. Their lives would change while on vacation in Miami Beach when they were scouted to be models.',
        title: 'Riker Brothers',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FRikerBrothers.png?alt=media&token=53cc539e-baf2-47d2-a090-d687bff8af88',
      fontColor: '#6d9062',
      fontFamilyText: 'BaskervilleItalic',
      mail: 'studio@rikerbrothers.com',
      name: 'Riker Brothers',
      rating: 4,
      category: 'photography',
      width: 300,
    }],
    image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/icon%2Fcomunities%2Fphotographer.png?alt=media&token=0d1bf54e-c0a7-410f-a4c6-305c25785b56',
    name: 'PHOTOGRAPHY',
  }, {
    companies: [{
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FWhitneyJohns1.jpg?alt=media&token=4b1ec6b6-d8a6-47d0-a231-299bd4fb2d2b',
        sub_title: 'FIT with WHIT APP',
        text: 'With my schedule, I’m usually squeezing in a workout between clients and don’t have the ability or time to take off my full face of makeup for the workout.',
        title: 'Let me be your trainer!',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FWhitneyJohns2.jpg?alt=media&token=bdef281a-699b-4c81-9cda-d206505d6d47',
        sub_title: 'FIT with WHIT APP ',
        text: '120 different workouts, over 250 exercises',
        title: 'Let me be your trainer!',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FWhitneyJohns.jpg?alt=media&token=f25245a9-a837-4fc2-95a8-9793fe56aa34',
      fontColor: '#6421b7',
      fontFamilyText: 'SukhumvitSetBold',
      height: 250,
      mail: 'contact@whitneyjohns.com ',
      name: 'Whitney Johns',
      rating: 5,
      category: 'crossFit',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fwoodsfit1.jpg?alt=media&token=a5c5297c-03fb-40a9-9f75-22cdd06dca84',
        sub_title: "D'JUAN'S PERSONAL TRANSFORMATION",
        text: 'As the Equinox Prodigy winner in 2017, D’Juan continues to strive for the best. He has recently set his focus on training programs that are very distinct in the fitness world and have delivered amazing results! His programs are based on an athletes willingness to move forward in fitness like himself or anyone who feels that enough is enough and wants to improve there body. Don’t be deceived by other training programs, D’Juan Woods offers detailed  comprehensive personal training programs that will improve your physical condition in a matter of weeks!',
        title: 'Let me be your trainer!',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fwoodsfit2.jpg?alt=media&token=88f3a4a4-f56d-498c-884c-3d596f75c32d',
        sub_title: 'NIKE MASTER TRAINER',
        text: 'In 2015, D’Juan was chosen as a trainer for Nike Training Club, led by some of the world’s preeminent trainers. In 2017, D’Juan was named as a Master Trainer for the Nike Training Club.',
        title: 'Let me be your trainer!',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fwoodsfit.png?alt=media&token=62ba4eae-6d0f-461f-85a7-025168aa6945',
      fontColor: '#a21419',
      fontFamilyText: 'AvenirLight',
      mail: 'juanwoods@gmail.com',
      name: "D' Juan Woods",
      rating: 5,
      category: 'personal Trainers',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FRonBoss1.jpg?alt=media&token=09551bb2-fbf9-4812-b5fa-1fcff8e41feb',
        sub_title: 'JUST TRAIN YOUR MIND AND YOUR BODY WILL FOLLOW',
        text: 'Summer is right around the corner and we all are gearing up for our 2018 summer bods! But for some of us, that summer body feels out of reach because of the excess fat we may be currently carrying.',
        title: 'Fat Loss',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FRonBoss2.jpg?alt=media&token=b5929dd1-628e-4048-a2e2-6fd04b112765',
        sub_title: 'JUST TRAIN YOUR MIND AND YOUR BODY WILL FOLLOW',
        text: 'In today’s day and age, most people work behind a desk. As life becomes more technologically advanced, our jobs become less mobile. We sit behind a computer, often only getting up for bathroom breaks or lunch, then commute home to sit in front of a television and unwind.',
        title: 'How to Keep Moving When You Have a Desk Job',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FRonBoss.jpg?alt=media&token=d1422115-6eef-461b-a34d-574cf251141b',
      fontColor: '#6894af',
      fontFamilyText: 'ERBukinistMacBold',
      height: 250,
      mail: 'info@killermerch.com',
      name: 'Ron Boss Everline',
      rating: 5,
      category: 'psychology',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FEddieArrozola2.png?alt=media&token=7f218f0c-3609-45c4-80c7-acb030f11102',
        sub_title: 'Let me be your trainer!',
        text: 'Training in a group or "Pack," allows all the benefits, support, and motivation that only teamwork can provide to advance your training. From training with friends to opponents that highlight technique areas, Pack Training is always a great addition to your training regiment.',
        title: 'Pack training',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FEddieArrozola.png?alt=media&token=11b867cd-0509-4540-b778-9ad2f66f7104',
      fontColor: '#6d9062',
      fontFamilyText: 'BaskervilleItalic',
      mail: 'eddie@wolfpackteamtraining.com',
      name: 'Eddie Arrozola',
      rating: 5,
      category: 'personal Trainers',
      width: 200,
    }],
    image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/icon%2Fcomunities%2Ffitness.png?alt=media&token=390fd5bb-6a09-4149-ac55-ee980aaee7a6',
    name: 'FITNESS',
  }, {
    companies: [{
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FLookAtEye.jpg?alt=media&token=f779bf1a-6f60-4d30-a984-fe6916df9f18',
        sub_title: '- Mine do! ',
        text: 'Thanks for trusting me to creative direct this look.',
        title: 'Do your eyes light up when your client walks into the room?',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FToyeadedipe.jpg?alt=media&token=2d2fd8a6-3d0c-43f8-bf95-14cbcde1e12e',
      fontColor: '#6421b7',
      fontFamilyText: 'SukhumvitSetBold',
      height: 250,
      mail: 'toyeadedipe@gmail.com',
      name: 'Toye Adedipe',
      rating: 5,
      category: 'wardrobe',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FToyeadedipe1.jpg?alt=media&token=cb39d33f-8730-41ff-82c8-6da73028ae5d',
        sub_title: '- Mine do! ',
        text: 'Thanks for trusting me to creative direct this look.',
        title: 'Do your eyes light up when your client walks into the room?',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FJoubertstyling.jpg?alt=media&token=18fdfcf9-b328-404b-bd2d-d3a3baeeb244',
      fontColor: '#a21419',
      fontFamilyText: 'AvenirLight',
      height: 250,
      mail: 'joubertstyling@gmail.com',
      name: 'Catherine Joubert',
      rating: 5,
      category: 'hair',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FErinMicklow1.jpg?alt=media&token=0ebcb9e7-8a5b-4b7c-a2e6-1a4485497d87',
        sub_title: 'Designs by Erin Micklow',
        text: "Custom studded vests & jackets for men & women designed & hand crafted by Erin are available made to order. Erin's vests are sturdy & proven to stand up through years of wear. Contact me to discuss your custom order!",
        title: 'STUDDED VESTS/JACKETS/WARDROBE',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FErinMicklow.jpg?alt=media&token=729fde76-e191-44ba-a7e0-b50eea9946a1',
      fontColor: '#6894af',
      fontFamilyText: 'ERBukinistMacBold',
      height: 250,
      mail: 'Erin@ErinMicklowStylist.com ',
      name: 'Erin Micklow',
      rating: 5,
      category: 'wardrobe',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FTiffany1.png?alt=media&token=1fd1819b-3cf5-4ad7-ba6d-293f919ff949',
        sub_title: 'Designs by Ray Fisher',
        text: 'Step into Success',
        title: 'Ray Fisher',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FTiffany.jpeg?alt=media&token=845b412c-e4ad-42b3-ab71-208695b3350e',
      fontColor: '#6d9062',
      fontFamilyText: 'BaskervilleItalic',
      height: 280,
      mail: 'tiffani@tiffanichynel.com',
      name: 'Tiffani Chynel',
      rating: 4,
      category: 'makeup',
    }],
    image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/icon%2Fcomunities%2Fstylist.png?alt=media&token=7f777b68-74da-49d8-b0f9-cfdcdb861ef6',
    name: 'STYLING',
  }, {
    companies: [{
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fmagnolia1.png?alt=media&token=b60a7ab0-a99c-4353-8533-1f2206b26c63',
        sub_title: 'Elizabeth Brooks Oakley M.S. CCC-SLP',
        text: 'I was initially drawn to the profession of speech-language pathology because I wanted to work with pediatric and adult clients in voice disorders. As a trained theater actor and singer, it seemed like a natural fit. I love working to improve the voice in not just performers, but anyone who has challenges with vocal function. I became certified early in my career in Lee Silverman Voice Therapy (LSVT), which is voice therapy for individuals with Parkinson’s disease (PD).  While I truly enjoy working in voice disorders, I soon realized that my passion is helping any patient with their individual communication needs.',
        title: 'ABOUT THE OWNER',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fmagnolia2.png?alt=media&token=489e3832-1ac5-4f72-9b1a-f7f2489b02b3',
        sub_title: 'San Fernando Valley clinic.',
        text: 'Magnolia Speech Therapy offers comprehensive services to pediatric and adult populations in the San Fernando Valley clinic and in-home across Greater Los Angeles. Our goal is to provide you with the most effective therapy and home-based strategies that are customized to ensure your greatest success. Please call us for more information on how we can serve you and your family.',
        title: 'WELCOME TO MAGNOLIA SPEECH THERAPY',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fmagnolia-speech-therapy.jpg?alt=media&token=7f6f8114-b904-40fa-95f8-c4408e9bc770',
      fontColor: '#6421b7',
      fontFamilyText: 'SukhumvitSetBold',
      mail: 'info@magnoliaspeechtherapy.com',
      name: 'Speech Therapy',
      rating: 5,
      category: 'alternative',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fwellington.png?alt=media&token=423a7576-851e-423b-ab0b-98242daedd08',
        sub_title: '“Actors are people, only more so.”',
        text: 'It’s not usual to think of actors as a special-needs population, but the acting profession places special demands on the body, mind, and spirit. The body is the actor’s instrument, much as the piano or saxophone would be for a musician. Like the piano, the actor’s body requires maintenance and occasional tuning in order to function optimally. If the actor’s instrument is out of tune, the performance will suffer. An actor whose muscles are stiff, sore, or shortened will be more likely to render a stiff performance lacking range and subtlety.',
        title: 'Massage for Actors, Musicians, and Artists',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fwellington-massage.jpg?alt=media&token=dd438417-6aac-4f65-b2b8-77a6d65069b1',
      fontColor: '#a21419',
      fontFamilyText: 'AvenirLight',
      mail: 'massagetherapy@gmail.com',
      name: 'Massage Therapy',
      rating: 5,
      category: 'physical',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fbodytuning1.png?alt=media&token=c8a0a5a6-177a-435e-adb8-450b9c6fdce8',
        sub_title: 'Unique care needed by performing artists.',
        text: 'Formerly located at Carnegie Hall, the Body Tuning Studio is now in central Manhattan at Columbus Circle. The opposite of a clinical setting, it is an oasis of calm. Before treatment, clients are seated on vintage Carnegie Hall seats and listen to classical music, surrounded by photographs of famous musicians, dancers and artists who have been treated by Shmuel Tatz. The Studio runs on time and rarely does a client have to wait for their session to begin. There are four individual treatment rooms which look out on a beautiful garden.',
        title: 'About the Studio',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fbody-tuning-physical-therapy.png?alt=media&token=3328458b-574f-4760-9c92-df919fb73dbf',
      fontColor: '#6894af',
      fontFamilyText: 'ERBukinistMacBold',
      mail: 'physicaltherapy@gmail.com ',
      name: 'Physical Therapy',
      rating: 5,
      category: 'physical',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fbonnierae1.png?alt=media&token=75f9c1b9-557f-4aae-a352-6d8300aa3728',
        sub_title: 'When you touch one thing with deep awareness, you touch everything.',
        text: 'I am a Licensed Marriage and Family Therapist, LMFT 91089. Along with seeing clients in my private practice, I am an adjunct instructor in the Masters of Clinical Psychology program at Antioch University, teaching workshops devoted to helping budding therapists work with queer and lesbian identified women through an LGBTQ affirmative lens.',
        title: 'About Bonnie Rae',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FBonnierae2.png?alt=media&token=f27fce89-97f5-485a-a520-b6d78c4c5d95',
        sub_title: 'The Daunting Task of Finding a Therapist in LA',
        text: 'The truth is, Los Angeles is saturated with psychotherapists. If you go to the popular therapist search website, Psychology Today, you will probably find a lengthy list of therapists in your area. That being said, why the hell is finding a therapist so hard?!',
        title: 'This Shouldn’t Be So Hard.',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FBonnie-ray-psy.png?alt=media&token=c76c488a-e691-4491-893c-305b6ef17e1c',
      fontColor: '#6d9062',
      fontFamilyText: 'BaskervilleItalic',
      mail: 'psychotherapy@gmail.com',
      name: 'Psycho Therapy',
      rating: 4,
      category: 'psycho',
    }],
    image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/icon%2Fcomunities%2Ftherapy.png?alt=media&token=b5a25070-5346-4512-8783-0882e94983e1',
    name: 'THERAPY',
  }, {
    companies: [{
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fedge1.png?alt=media&token=f20a92dd-4c9e-4e82-9f16-ecd9b218f58c',
        sub_title: 'THE IDEAL LOCATION FOR PHOTOSHOOTS',
        text: 'Our newly-renovated studios are clean, industrial, open spaces that are the ideal location for photoshoots or for use as event venues for creative professionals. We have quickly become the trusted resource for the mid-city photo district and beyond.',
        title: 'STUDIOS',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fedge2.png?alt=media&token=f1d7d4a9-7859-4d62-8c04-4f6fd8de2c6a',
        sub_title: 'Hold up to 450 guests!',
        text: 'EDGE studios has played the perfect venue for everything from weddings to workshops. We have over 5,000 sq. ft. of indoor/outdoor space conveniently located in the heart of Mid City, Los Angeles — at the intersection of Hollywood, DTLA, & Culver City. Our studio spaces combined can hold up to 450 guests (250 seated), where we’ve accommodated everything from exotic animals to exotic cars, castings to conferences, weddings to workshops, private dinners, premieres, gallery openings, birthdays, bar/bat mitzvahs, quincañeras, castings, sample sales, product launches, and then some.',
        title: 'Perfect venue for everything!',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fedge.png?alt=media&token=9b6111b6-d33e-429e-af63-6cb0098ec018',
      fontColor: '#6421b7',
      fontFamilyText: 'SukhumvitSetBold',
      mail: 'edge@gmail.com',
      name: 'EDGE',
      rating: 5,
      width: 300,
      category: 'events',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Falternative_rentals.png?alt=media&token=51961b0c-19f6-499a-8d11-99d6b0d70948',
        sub_title: 'Giving clients first class service is our primary goal.',
        text: 'Alternative Rentals is a digital camera rental company with locations in Los Angeles, California and Atlanta, Georgia. We are determined to provide your production with high-end digital equipment at competitive prices. We rent cameras by ARRI (SXT, XT, Amira, Alexa Mini), RED (Dragon, Weapon), SONY (F65, F55, FS7), Panasonic (Varicam35) and much more.',
        title: 'Digital Cinema is our passion.',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FalternativeRentals_logo.jpg?alt=media&token=6df37e24-ab1e-4e76-a0de-0e1ece4e397b',
      fontColor: '#a21419',
      fontFamilyText: 'AvenirLight',
      mail: 'alternative@gmail.com',
      name: 'ALTERNATIVE',
      rating: 5,
      category: 'rental',
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FBirns1.png?alt=media&token=02e74054-ec4d-4468-b7f1-cf372262bd79',
        sub_title: 'Collaboration with @panasonicusa',
        text: 'We are so grateful for all of our clients, partners and collaborators. YOU are the reason we are excited to come to work in the morning! Speaking of collaboration and education, we could not ask for a better collaborator than @panasonicusa.A special shout - out to Steve Slade and Laurence Nunn for taking time out of their busy schedule to help train our staff on the #EVA1 and #VaricamLT systems.Stay tuned to our social media channels as more #panasonic related news is coming soon!',
        title: 'YOU are the reason!',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fbirns2.png?alt=media&token=ba2f3c6b-62bf-401c-8b1f-7cf0b6275f9b',
        sub_title: 'Doors open at 6pm.',
        text: 'Please join us for a complimentary evening with Panasonic Camera Experts to demo the Panasonic Varicam Family, including the brand new EVA-1! Doors open at 6pm.Our event will be short, with refreshments and our favorite bluegrass band, Possum.If you are interested in attending, please RSVP at birnsandsawyerevents@gmail.com',
        title: 'SHOWCASING THE NEW PANASONIC EVA-1',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2FbirnSawyer.jpg?alt=media&token=215ca8a6-ada0-4ac4-bcfd-62f137f2dcbc',
      fontColor: '#6894af',
      fontFamilyText: 'ERBukinistMacBold',
      mail: 'birnssawyer@gmail.com ',
      name: 'BIRNS & SAWYER',
      rating: 5,
      category: 'rental',
      width: 200,
    }, {
      articles: [{
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fkeslow1.png?alt=media&token=237fbc09-7278-49fc-950f-63cc0deac2b6',
        sub_title: 'Not just today but everyday!',
        text: 'At Keslow Camera we celebrate the highly talented and driven women in our offices around North America, not just today but everyday! [NOT PICTURED: Mel Mathis, SVP, Marketing]',
        title: 'Happy #IWD2018!',
      }, {
        image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fkeslow2.png?alt=media&token=8ea9040d-5d57-4d65-b375-dcf8b0b83064',
        sub_title: 'Are you ready for a new shooting experience?',
        text: 'Introducing the VariCam PURE, offering 4K uncompressed V-RAW at up to 120fps, now available for rental at Keslow Camera.',
        title: 'VariCam PURE',
      }],
      banner: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/communities%2Fkeslow-camera-logo.jpg?alt=media&token=68cc527b-604a-476f-9095-e820b5bccd73',
      fontColor: '#6d9062',
      fontFamilyText: 'BaskervilleItalic',
      mail: 'info@keslowcamera.com',
      name: 'KESLOW CAMERA',
      rating: 4,
      category: 'rental',
    }],
    image: 'https://firebasestorage.googleapis.com/v0/b/selftape-ef381.appspot.com/o/icon%2Fcomunities%2Fequipment.png?alt=media&token=4a805001-5a51-405a-a050-69293aff2c33',
    name: 'EQUIPMENT',
  },
];

export default firebasecommunities;
