import location1 from '../images/locations/west-hollywood.jpg';
import location2 from '../images/locations/EchoPark1.jpg';
import location3 from '../images/locations/lankershim.jpg';
import location4 from '../images/locations/santaMonica.jpg';
import location5 from '../images/locations/midCity.jpg';
import Json from '../images/locations/practitioners/JasonMontgomery.png';
import Jhonathan from '../images/locations/practitioners/JonathanKarp.png';
import Mallory from '../images/locations/practitioners/MalloryMcCree.png';
import Pancho from '../images/locations/practitioners/Pancho.png';
import Luckas from '../images/locations/practitioners/Luckas.png';
import Peter from '../images/locations/practitioners/Peter.png';
import Grece from '../images/locations/practitioners/Grace.png';
import Angela from '../images/locations/practitioners/Angela.png';
import CheriseBoothe from '../images/locations/practitioners/CheriseBoothe.jpg';
import LarryPowell from '../images/locations/practitioners/LarryPowell.jpg';
import JsonSetup from '../images/profile/studiya.jpg';
import PanchoSetup from '../images/profile/panchoSetup.jpg';
import PeterSetup from '../images/profile/PeterSetup.jpeg';
import CheriseBootheSetup from '../images/profile/CheriseBootheSetup.jpg';
import LarryPowellSetup from '../images/profile/LarryPowellSetup.png';
import Grace from '../images/locations/practitioners/grace.jpg';

const locationList = [
  {
    id: 0,
    name: 'WEST HOLLYWOOD',
    img: location1,
    practitioners: [
      {
        id: 0,
        rating: 5,
        username: 'Jason Montgomery',
        value: 'Jason Montgomery (Practitioner)',
        password: '123456234',
        role: 'practitioner',
        joined: 'Nov \'14',
        image: Json,
        setup: JsonSetup,
        location: {
          latitude: 34.0984311,
          longitude: -118.3658692,
        },
        email: 'jason@selftape.com',
        phone: '1 626-676-3243',
        address: '1509 N Crescent Heights Blvd #4, West Hollywood, CA 90046',
        total: 80,
        bio: `Casting Director, Producer, and Digital Handyman Jason Montgomery is a MFA film school graduate from the New York Film Academy, Universal Studios. He began his entertainment career after graduating with honors from the University at Albany in New York where he was Pre-Law with a double major in Political Theory and Classical Theater. After a successful stint on Broadway, he moved to Los Angeles in the Summer of 2003.${'\n\n'}He has worked in every facet of the entertainment industry from PA to Director. In 2008, while working as the Director of US Operations for Casting Workbook, he was given the oppertunity to be part of the casting team at 20th Century Fox and helped cast over 30 feature films as a Casting Associate including 127 Hours, X-Men First Class, Prometheus, Life Of Pi and many more. Being in the room and watching how Danny Boyle, Ang Lee, McG, and Shawn Levy worked with actors was an invaluable education to him.`,
        reviews: [],
      },
      {
        id: 1,
        rating: 5,
        value: 'Pancho Moler (Practitioner)',
        username: 'Chris Pascal',
        password: '4234235435',
        role: 'practitioner',
        joined: 'Oct \'1',
        image: Pancho,
        setup: PanchoSetup,
        location: {
          latitude: 34.0773798,
          longitude: -118.385536,
        },
        email: 'pancho@selftape.com',
        phone: '1 354-543-5645',
        address: '8789 Beverly Blvd, Los Angeles, CA 90048',
        total: 30,
        bio: 'Born in Santiago Chile, Pancho moved to the United States at age 8. At 18 he kept on traveling as a professional skateboarder. Pancho is the first professional Little Person skateborder in the world. Pancho began studying acting with Robert Rusler at The Hollywood Playground. Then with Metthew Barry at the Working Actor. Also, He is the midst of traning with Upright Citizens Brigade. Most recently, Pancho became aWorking Finalist at the world renowned Actor\'s Studio and has starred in two Rob Zombie films.',
        reviews: [],
      },
      {
        id: 2,
        rating: 5,
        value: 'Mia Redwood (Practitioner)',
        username: 'Mia Redwood',
        password: '4234235435',
        role: 'practitioner',
        joined: 'Oct \'1',
        image: Grace,
        setup: PanchoSetup,
        location: {
          latitude: 34.0773798,
          longitude: -118.385536,
        },
        email: 'pancho@selftape.com',
        phone: '1 354-543-5645',
        address: '8789 Beverly Blvd, Los Angeles, CA 90048',
        total: 30,
        bio: 'Born in Santiago Chile, Pancho moved to the United States at age 8. At 18 he kept on traveling as a professional skateboarder. Pancho is the first professional Little Person skateborder in the world. Pancho began studying acting with Robert Rusler at The Hollywood Playground. Then with Metthew Barry at the Working Actor. Also, He is the midst of traning with Upright Citizens Brigade. Most recently, Pancho became aWorking Finalist at the world renowned Actor\'s Studio and has starred in two Rob Zombie films.',
        reviews: [],
      },
      {
        id: 2,
        rating: 5,
        value: 'Mia Redwood (Practitioner)',
        username: 'Kristen Love',
        password: '4234235435',
        role: 'practitioner',
        joined: 'Oct \'1',
        image: CheriseBoothe,
        setup: PanchoSetup,
        location: {
          latitude: 34.0773798,
          longitude: -118.385536,
        },
        email: 'pancho@selftape.com',
        phone: '1 354-543-5645',
        address: '8789 Beverly Blvd, Los Angeles, CA 90048',
        total: 30,
        bio: 'Born in Santiago Chile, Pancho moved to the United States at age 8. At 18 he kept on traveling as a professional skateboarder. Pancho is the first professional Little Person skateborder in the world. Pancho began studying acting with Robert Rusler at The Hollywood Playground. Then with Metthew Barry at the Working Actor. Also, He is the midst of traning with Upright Citizens Brigade. Most recently, Pancho became aWorking Finalist at the world renowned Actor\'s Studio and has starred in two Rob Zombie films.',
        reviews: [],
      },
      {
        id: 2,
        rating: 5,
        value: 'Mia Redwood (Practitioner)',
        username: 'Jacob Turner',
        password: '4234235435',
        role: 'practitioner',
        joined: 'Oct \'1',
        image: Peter,
        setup: PanchoSetup,
        location: {
          latitude: 34.0773798,
          longitude: -118.385536,
        },
        email: 'pancho@selftape.com',
        phone: '1 354-543-5645',
        address: '8789 Beverly Blvd, Los Angeles, CA 90048',
        total: 30,
        bio: 'Born in Santiago Chile, Pancho moved to the United States at age 8. At 18 he kept on traveling as a professional skateboarder. Pancho is the first professional Little Person skateborder in the world. Pancho began studying acting with Robert Rusler at The Hollywood Playground. Then with Metthew Barry at the Working Actor. Also, He is the midst of traning with Upright Citizens Brigade. Most recently, Pancho became aWorking Finalist at the world renowned Actor\'s Studio and has starred in two Rob Zombie films.',
        reviews: [],
      },
    ],
  },
  {
    id: 1,
    name: 'ECHO PARK',
    img: location2,
    practitioners: [
      {
        id: 0,
        rating: 5,
        value: 'Cherise Boothe (Practitioner)',
        name: 'Cherise Boothe',
        password: '324234',
        role: 'practitioner',
        joined: 'Apr \'12',
        image: CheriseBoothe,
        setup: CheriseBootheSetup,
        location: {
          latitude: 34.0690194,
          longitude: -118.2714277,
        },
        email: 'cherise@selftape.com',
        phone: '1 122-435-5345',
        address: '245 N Alvarado St. LA, CA 90026',
        total: 30,
        bio: 'Cherise Boothe -  has worked extensively in theater, film, television, and narration. She has appeared in numerous regional plays, as well as in television shows such as The Good Wife, Law & Order: SVU, and Gossip Girl. She holds an MFA in acting from New York University. She was a finalist in 2015 for the prestigious Audie Award for best multivoiced narration.',
        reviews: [
          {
            name: 'Sheldon Braton',
            rating: 3,
            part_one: 'Samsung Galaxy S2 skyrocket android 4.1 jellybean',
            part_two: 'You can click year make and model but the moment',
          },
          {
            name: 'A Google User',
            rating: 2.5,
            part_one: 'Not Bad ...',
            part_two: 'WHY better than those Samsung Galaxy S2 skyrocket',
          },
        ],
      },
      {
        id: 1,
        rating: 5,
        value: 'Larry Powell (Practitioner)',
        name: 'Larry Powell ',
        password: '4234235435',
        role: 'practitioner',
        joined: 'Jan \'1',
        image: LarryPowell,
        setup: LarryPowellSetup,
        location: {
          latitude: 34.0883833,
          longitude: -118.2612539,
        },
        email: 'larry@selftape.com',
        phone: '1 324-543-5435',
        address: '1822 Glendale Blvd LA, CA 90026',
        total: 30,
        bio: 'Larry Powell -  is a multi-hyphenate artist hailing from South Central Los Angeles but based in New York City. He holds a BFA in Theatre Arts from Carnegie Mellon University. Writing plays since he was twelve years old, on the backs of brown paper shopping bags when he had no writing paper, while known mostly as a successful theatre actor, Larry is a writer first.',
        reviews: [
          {
            name: 'Sheldon Braton',
            rating: 3,
            part_one: 'Samsung Galaxy S2 skyrocket android 4.1 jellybean',
            part_two: 'You can click year make and model but the moment',
          },
          {
            name: 'A Google User',
            rating: 2.5,
            part_one: 'Not Bad ...',
            part_two: 'WHY better than those Samsung Galaxy S2 skyrocket',
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: 'NORTH HOLLYWOOD',
    img: location3,
    practitioners: [
      {
        id: 0,
        rating: 2.5,
        value: 'Jonathan Karp (Practitioner)',
        name: 'Jonathan Karp',
        password: '4234235435',
        role: 'practitioner',
        joined: 'Jan \'1',
        image: Jhonathan,
        setup: JsonSetup,
        location: {
          latitude: 34.1717881,
          longitude: -118.4376204,
        },
        email: 'jonathan@selftape.com',
        phone: '1 333-543-6546',
        address: '13860 Burbank Blvd Los Angeles, CA 91401',
        total: 30,
        bio: 'A true NY native, born and raised, new to LA! I went to SUNY New Paltz where I received my undergrad degree in theater, & then onto Rutgers Univ. Mason Gross School of the Arts for my MFA in acting.',
        reviews: [
          {
            name: 'Sheldon Braton',
            rating: 3,
            part_one: 'Samsung Galaxy S2 skyrocket android 4.1 jellybean',
            part_two: 'You can click year make and model but the moment',
          },
          {
            name: 'A Google User',
            rating: 2.5,
            part_one: 'Not Bad ...',
            part_two: 'WHY better than those Samsung Galaxy S2 skyrocket',
          },
        ],
      },
      {
        id: 1,
        rating: 4,
        value: 'Peter Macaluso (Practitioner)',
        name: 'Peter Macaluso',
        password: '4234235435',
        role: 'practitioner',
        joined: 'Feb \'14',
        image: Peter,
        setup: PeterSetup,
        location: {
          latitude: 34.1844501,
          longitude: -118.3879868,
        },
        email: 'peter@selftape.com',
        phone: '1 765-234-8797',
        address: '6240 Lankershizm Blvd, North Hollywood, CA 91601',
        total: 30,
        bio: 'Peter Macaluso ia a LA/NYC based filmmaker. He founded Macarony Productions in 2005 and directed three no-budget feature length films by the age of 23. He produced a 104 episode comedy webseries, Nepotism, from 2013-2015. It had multiple episodes featured by Funny or Die. He\'s worked with companies like Above, Average, AskMen, BMW, Buzzfeed, CollegeHumor, Cracked, Loot Crate, Funny or Die, PIT, and UCB! He can write, direct, produce, edit, shoot, production design, juggle, poorly, speak in the third-person, and make a mean lasagna.',
        reviews: [
          {
            name: 'Sheldon Braton',
            rating: 3,
            part_one: 'Samsung Galaxy S2 skyrocket android 4.1 jellybean',
            part_two: 'You can click year make and model but the moment',
          },
          {
            name: 'A Google User',
            rating: 2.5,
            part_one: 'Not Bad ...',
            part_two: 'WHY better than those Samsung Galaxy S2 skyrocket',
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: 'SANTA MONICA',
    img: location4,
    practitioners: [
      {
        id: 0,
        rating: 5,
        value: 'Lucas Jackson (Practitioner)',
        name: 'Lucas Jackson',
        password: '4234235435',
        role: 'practitioner',
        joined: 'Nov \'14',
        image: Luckas,
        setup: JsonSetup,
        location: {
          latitude: 34.0308284,
          longitude: -118.4987351,
        },
        email: 'luckas@selftape.com',
        phone: '1 675-244-1232',
        address: '1238 Montana Ave, Santa Monica, CA 900403',
        total: 30,
        bio: 'Lucas Jackson is a business development specialist of e-commerce based marketplaces, conceptualization, culture, and design. Mr Jackson is also a classically trained actor with a focus on in-depth text, Shakespeare, and language and accent driven material. In addition to his experience in theater, film, and television, Luke is an experienced and proven entrepreneur.',
        reviews: [
          {
            name: 'Sheldon Braton',
            rating: 3,
            part_one: 'Samsung Galaxy S2 skyrocket android 4.1 jellybean',
            part_two: 'You can click year make and model but the moment',
          },
          {
            name: 'A Google User',
            rating: 2.5,
            part_one: 'Not Bad ...',
            part_two: 'WHY better than those Samsung Galaxy S2 skyrocket',
          },
        ],
      },
      {
        id: 1,
        rating: 5,
        value: 'Grace De Silva (Practitioner)',
        name: 'Grace De Silva',
        password: '4235435',
        role: 'practitioner',
        joined: 'Nov \'14',
        image: Grece,
        setup: JsonSetup,
        location: {
          latitude: 34.0167434,
          longitude: -118.4998925,
        },
        email: 'grece@selftape.com',
        phone: '1 543-456-1233',
        address: '1310 3rd St, Santa Monica, CA 90401',
        total: 30,
        bio: 'Grace De Silva works both in English and Spanish Markets as an actor, voice-over, artist, director and produces her own content.',
        reviews: [
          {
            name: 'Sheldon Braton',
            rating: 3,
            part_one: 'Samsung Galaxy S2 skyrocket android 4.1 jellybean',
            part_two: 'You can click year make and model but the moment',
          },
          {
            name: 'A Google User',
            rating: 2.5,
            part_one: 'Not Bad ...',
            part_two: 'WHY better than those Samsung Galaxy S2 skyrocket',
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: 'MID CITY',
    img: location5,
    practitioners: [
      {
        id: 0,
        rating: 4.5,
        value: 'Angela Lewis (Practitioner)',
        name: 'Angela Lewis',
        password: '4235435435',
        role: 'practitioner',
        joined: 'Feb \'14',
        image: Angela,
        setup: JsonSetup,
        location: {
          latitude: 34.069972,
          longitude: -118.3457354,
        },
        email: 'angela@selftape.com',
        phone: '1 324-765-2355',
        address: '260 S LA BREA AVE LOS ANGELES, CA 90036',
        total: 30,
        bio: 'Currently starring on FX\'s, \'Snowfall\', which she booked from self-tape, Angela has tons of experience coaching and directing actors.',
        reviews: [
          {
            name: 'Sheldon Braton',
            rating: 3,
            part_one: 'Samsung Galaxy S2 skyrocket android 4.1 jellybean',
            part_two: 'You can click year make and model but the moment',
          },
          {
            name: 'A Google User',
            rating: 2.5,
            part_one: 'Not Bad ...',
            part_two: 'WHY better than those Samsung Galaxy S2 skyrocket',
          },
        ],
      },
      {
        id: 1,
        rating: 5,
        value: 'J. Mallory McCree (Practitioner)',
        name: 'J. Mallory McCree',
        password: '324234',
        role: 'practitioner',
        joined: 'Sep \'12',
        image: Mallory,
        setup: JsonSetup,
        location: {
          latitude: 34.0356068,
          longitude: -118.3412476,
        },
        email: 'mallory@selftape.com',
        phone: '1 122-786-5345',
        address: '2314 West Blvd, Los Angeles, CA 90016',
        total: 70,
        bio: 'J. Mallory McCree is an accomplished actor having booked major roles on Homeland, Quantico, and Law & Order via self-tape. With a BFA from Rutgers University, Mr. McCree has been working consistently as an actor since graduation. From Broadway to feature films, J. Mallory has gained much experience and has become extremely familiar with the audition process and the industry\'s new standard of the self-tape. Understanding how vital it is to produce a great convenient. Simply, an actor looking out for actors. Mr. McCree leads the SELFTAPE NOW team in strategic branding and culture development. ',
        reviews: [
          {
            name: 'Sheldon Braton',
            rating: 3,
            part_one: 'Samsung Galaxy S2 skyrocket android 4.1 jellybean',
            part_two: 'You can click year make and model but the moment',
          },
          {
            name: 'A Google User',
            rating: 2.5,
            part_one: 'Not Bad ...',
            part_two: 'WHY better than those Samsung Galaxy S2 skyrocket',
          },
        ],
      },
    ],
  },
];
export default locationList;
